default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  statement_timeout: 5000
  insert_returning: true

development:
  <<: *default
  database: sample-updating-app_development

test:
  <<: *default
  database: sample-updating-app_test

production:
  <<: *default
  database: sample-updating-app_production
  username: sample-updating-app
  password: <%= ENV['SAMPLE-UPDATING-APP_DATABASE_PASSWORD'] %>
